Fix doodle/calendar icon positions
fkaelberer/bvbbpp pull request #15
Opened 2016-10-21 21:24 UTC by martingruhn

Fix für #10 und #14. Bäm!

2016-10-21 21:26 UTC, martingruhn commented
Hoppla, in diesem pull request sind zu viele commits drin. Korrigiere ich später...

2016-10-22 08:59 UTC, martingruhn commented
Ehrlich gesagt ist mir unklar, wie das vorher funktionieren konnte. Deshalb gern kritisch reviewen.

2016-10-22 09:06 UTC, martingruhn commented
Schaue später mal, wie man die Selektion der Elemente generell verbessern könnte.

2016-10-22 23:02 UTC, fkaelberer requested changes
Hi Martin, vielen Dank für den Fix, ich hab mich immer gescheut, und habe, wenn ich Zeit hatte lieber unleserlichen Code refaktoriert. Ich denke, wenn dein Patch durch ist, kann Version 1.4 online gehen, aber ich hätte da noch ein paar Wünsche :-). 

> Ehrlich gesagt ist mir unklar, wie das vorher funktionieren konnte. 

Ich hab mich auch gefragt, warum noch nicht mal die Anzahl der Doodle-Knöpfe stimmt. Entweder hängt es damit zusammen, dass jetzt die Präferenzen asynchron abgefragt werden, und die Doodle-Link-Bearbeitung jetzt erst stattfindet, nachdem die Seite auf andere Weise verändert wurde. Oder es hat sich in dieser Saison serverseitig die Seitenstruktur verändert.

> Schaue später mal, wie man die Selektion der Elemente generell verbessern könnte. 

Mit `document.querySelectorAll("h4 table")` bekommst du genau die Tabellen mit den Spielterminen, und mit `document.querySelectorAll("h2:nth-of-type(n+2) table")` bekommst die Überschriften darüber. Zumindest im Originaldokument; falls das Dokument zu dem Zeitpunkt schon bearbeitet wurde, dann muss die Abfrage entsprechend geändert werden.

Falls du noch mehr Lust auf Refaktorierung hast, dann ist `Array.from()` praktisch damit man so etwas schreiben kann wie 

```
var queryResult = document.querySelectorAll("...")
Array.from(queryResult).forEach(table -> {
    addDoodleLinkUnderTable(table)
});
```

Falls du Lust hast, den Pull Request noch aufzuräumen, kannst du [deinen `master` branch auf meinen `master` branch rebasen](http://stackoverflow.com/questions/5968964/avoid-unwanted-merge-commits-and-other-commits-when-doing-pull-request-on-github), um die Merge-Commits zu verhindern. 

Und vielleicht hast du noch Lust, den neuen Bug #16 zu fixen?

Die Punkte mit "Lust" im Satz sind wirklich optional gemeint. Ich merge den Pull Request auch gerne rein, nachdem du den Titel nochmal angepasst hast (siehe Kommentar direkt am Code).

2016-10-22 23:02 UTC, fkaelberer commented on bvbbpp.js
> +    var title = "Spieltermine der " + tables[i+1].getElementsByTagName("div")[1].textContent;
Derzeit bekomme ich sowas wie "Spieltermine der Landesliga", vorher war's "Spieltermine der 3. Mannschaft". Das vorige Verhalten gefällt mir ein wenig besser.

2016-10-23 12:41 UTC, martingruhn commented
Auf die Schnelle habe ich den Doodle-Titel wunschgemäß angepasst und das Encoding in der Doodle-Description (#16) repariert. Pull request aufräumen war mir zu aufwändig. Soweit ich das verstehe, hat das aber keine negativen Auswirkungen auf Deinen Merge (d.h., die redundanten upstream merges werden nicht übernommen). Aber habe verstanden: Zukünftig rebase anstatt merge. Dann werden die pull requests übersichtlicher.

Außerdem vielen Dank für die anderen Hinweise! Hierzu ein paar Rückmeldungen:

> Ehrlich gesagt ist mir unklar, wie das vorher funktionieren konnte.
>> Ich hab mich auch gefragt, warum noch nicht mal die Anzahl der Doodle-Knöpfe stimmt. Entweder hängt es damit zusammen, dass jetzt die Präferenzen asynchron abgefragt werden, und die Doodle-Link-Bearbeitung jetzt erst stattfindet, nachdem die Seite auf andere Weise verändert wurde.

Ich glaube genau das. Vermutlich war die Tabelle mit aktuellen Termine ursprünglich noch nicht im DOM, als die Icons erstellt wurden. Damit ist alles um 1 Element verrutscht UND es wurden auch für die letzte Tabelle (Hallentermine) Icons erstellt. 

Zum Refactoring dieses Bereichs: Habe ich angefangen, aber uferte dann aus. Setze ich mich gern einen anderen Tag wieder ran. Mir ist schon aufgefallen, dass der Code zurzeit 3x über die Tabellen iteriert. Das ist ja Käse. Kannst Du mir offen lassen, musst Du aber nicht. Würde mir in dem Zusammenhang gern auch nochmal Gedanken über Testbarkeit machen. Sonst wird man ja verrückt beim Refactoring.

2016-10-23 15:44 UTC, merged

2016-10-23 15:57 UTC, fkaelberer commented
Ich hab die Kalendereinträge nochmal überprüft, die gehen auch. Vielen Dank für den Patch.

2016-10-25 18:24 UTC, fkaelberer commented
Hi Martin,
    
    deinen Branch hab ich reingemergt. Beim Mergen hatte ich übrigens
    die folgenden Optionen:
    
    
    Die Letzte der Optionen hat dabei nicht funktioniert: 
    
    Daher habe ich die zweite Option genommen. Deine ganzen
    Commit-Nachrichten wurden dann in einer Nachricht zusammengefasst,
    wobei ich dann noch "Fixes #14" usw. hinzugefügt habe, wodurch die
    Issues automatisch geschlossen wurden.
    
    
    Viele Grüße,
    
    Felix