Hallenbelegung enhancement
fkaelberer/bvbbpp pull request #3
Opened 2016-09-17 19:55 UTC by martingruhn

for Hallebenelegung do not only consider home matches but all matches in the home location

2016-09-21 21:41 UTC, fkaelberer commented on bvbbpp.js
> +    return s.locKey = homeLoc;
Das sollte ein `==` sein, oder?

2016-09-21 21:55 UTC, fkaelberer requested changes
Hi Martin, ich hatte deinen Code zwar gleich kommentiert, aber nicht gesehen, dass durch GitHubs neue Review-Funktion die Kommentare nicht gleich abgeschickt wurden, daher die späte Reaktion. 
Auf jeden Fall danke für den Patch. Allerdings scheint noch ein Fehler drin zu sein.

2016-09-22 18:51 UTC, martingruhn commented
Klar, Anfängerfehler. Wird man nie zu alt für. Besser ich nach. :-)


> Am 21.09.2016 um 23:55 schrieb Felix Kälberer <notifications@github.com>:
> 
> @fkaelberer requested changes on this pull request.
> 
> Hi Martin, ich hatte deinen Code zwar gleich kommentiert, aber nicht gesehen, dass durch GitHubs neue Review-Funktion die Kommentare nicht gleich abgeschickt wurden, daher die späte Reaktion. 
> Auf jeden Fall danke für den Patch. Allerdings scheint noch ein Fehler drin zu sein.
> 
> In bvbbpp.js:
> 
> >    spiele = spiele.filter(function(s) {
> -    return s.heimspiel;
> +    return s.locKey = homeLoc;
> Das sollte ein == sein, oder?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2016-09-24 12:32 UTC, martingruhn commented on bvbbpp.js
> +    return s.locKey = homeLoc;
ja. fixed.

2016-09-24 12:34 UTC, martingruhn commented
fixed.

2016-09-29 19:13 UTC, closed without merging

2016-10-01 22:15 UTC, fkaelberer commented
Hi Martin, Danke für den PR, auch wenn du ihn inzwischen wieder geschlossen hast. Ich habe ihn zum Anlass genommen, an der Stelle noch ein bisschen [weiter zu machen](https://github.com/fkaelberer/bvbbpp/commits/feature/fixPreferenceUsage). Also vielen Dank, dass du den Anfang gemacht hast.

2016-10-02 08:02 UTC, martingruhn commented
Cool. Gefällt mir.